// House Of Lyonez inventory.
// To edit a painting: change its title, price, or shipping below.
// To mark one sold: change  sold: false  to  sold: true
// Image for each painting lives at images/<id>.jpg
window.PAINTINGS = [
  { id: "white-rose", title: "White Rose", size: "10x20 in", thick: false, price: 120, shipping: 10, sold: false },
  { id: "pink-lily", title: "Pink Lily", size: "10x20 in", thick: false, price: 120, shipping: 10, sold: false },
  { id: "lavender-rose", title: "Lavender Rose", size: "10x20 in", thick: false, price: 120, shipping: 10, sold: false },
  { id: "coral-blue-rose", title: "Coral & Blue Rose", size: "10x20 in", thick: false, price: 120, shipping: 10, sold: false },
  { id: "crimson-dahlia", title: "Crimson Dahlia", size: "10x20 in", thick: false, price: 120, shipping: 10, sold: false },
  { id: "golden-sunflower", title: "Golden Sunflower", size: "10x20 in", thick: false, price: 120, shipping: 10, sold: false },
  { id: "midnight-rose", title: "Midnight Rose", size: "10x20 in", thick: false, price: 120, shipping: 10, sold: false },
  { id: "piano-dreams", title: "Piano Dreams", size: "12x16 in", thick: false, price: 120, shipping: 10, sold: false },
  { id: "butterfly-bloom", title: "Butterfly Bloom", size: "12x16 in", thick: false, price: 120, shipping: 10, sold: false },
  { id: "desert-saguaro", title: "Desert Saguaro", size: "12x16 in", thick: false, price: 120, shipping: 10, sold: false },
  { id: "heart-and-clock", title: "Heart & Clock", size: "11x14 in", thick: false, price: 95, shipping: 10, sold: false },
  { id: "green-pterodactyl", title: "Green Pterodactyl", size: "11x14 in", thick: false, price: 95, shipping: 10, sold: false },
  { id: "crimson-horizon", title: "Crimson Horizon", size: "14x11 in", thick: false, price: 95, shipping: 10, sold: false },
  { id: "the-gathering", title: "The Gathering", size: "12x9 in", thick: false, price: 75, shipping: 10, sold: false },
  { id: "sunflower-trio", title: "Sunflower Trio", size: "9x12 in", thick: false, price: 75, shipping: 10, sold: false },
  { id: "orange-poppy", title: "Orange Poppy", size: "9x12 in", thick: false, price: 75, shipping: 10, sold: false },
  { id: "red-tulip", title: "Red Tulip", size: "9x12 in", thick: false, price: 75, shipping: 10, sold: false },
  { id: "purple-tulip", title: "Purple Tulip", size: "9x12 in", thick: false, price: 75, shipping: 10, sold: false },
  { id: "rose-heart", title: "Rose Heart", size: "9x12 in", thick: false, price: 75, shipping: 10, sold: false },
  { id: "golden-wings", title: "Golden Wings", size: "10x8 in", thick: false, price: 60, shipping: 10, sold: false },
  { id: "coral-daisy", title: "Coral Daisy", size: "10x8 in", thick: false, price: 60, shipping: 10, sold: false },
  { id: "heart-on-blue", title: "Heart on Blue", size: "10x8 in", thick: false, price: 60, shipping: 10, sold: false },
  { id: "purple-skull", title: "Purple Skull", size: "10x8 in", thick: false, price: 60, shipping: 10, sold: false },
  { id: "bone-skull", title: "Bone Skull", size: "10x8 in", thick: false, price: 60, shipping: 10, sold: false },
  { id: "blue-blossoms", title: "Blue Blossoms", size: "10x8 in", thick: false, price: 60, shipping: 10, sold: false },
  { id: "carnation", title: "Carnation", size: "10x8 in", thick: false, price: 60, shipping: 10, sold: false },
  { id: "night-clouds", title: "Night Clouds", size: "10x8 in", thick: false, price: 60, shipping: 10, sold: false },
  { id: "violet-dahlia", title: "Violet Dahlia", size: "10x8 in", thick: false, price: 60, shipping: 10, sold: false },
  { id: "lily-and-gramophone", title: "Lily & Gramophone", size: "10x8 in", thick: false, price: 60, shipping: 10, sold: false },
  { id: "lion-sunflower-field", title: "Lion Sunflower Field", size: "10x8 in", thick: false, price: 60, shipping: 10, sold: false },
  { id: "golden-heart", title: "Golden Heart", size: "10x8 in", thick: false, price: 60, shipping: 10, sold: false },
  { id: "coral-bouquet", title: "Coral Bouquet", size: "10x8 in", thick: false, price: 60, shipping: 10, sold: false },
  { id: "first-life", title: "First Life", size: "5x7 in", thick: true, price: 45, shipping: 5, sold: false },
  { id: "little-one", title: "Little One", size: "5x7 in", thick: true, price: 45, shipping: 5, sold: false },
  { id: "sheltered", title: "Sheltered", size: "5x7 in", thick: true, price: 45, shipping: 5, sold: false },
  { id: "silver-rose", title: "Silver Rose", size: "5x7 in", thick: true, price: 45, shipping: 5, sold: false },
  { id: "sunset-tulip", title: "Sunset Tulip", size: "5x7 in", thick: false, price: 40, shipping: 5, sold: false },
  { id: "blue-rose", title: "Blue Rose", size: "5x7 in", thick: false, price: 40, shipping: 5, sold: false },
  { id: "calla-lilies-i", title: "Calla Lilies I", size: "5x7 in", thick: false, price: 40, shipping: 5, sold: false },
  { id: "calla-lilies-ii", title: "Calla Lilies II", size: "5x7 in", thick: false, price: 40, shipping: 5, sold: false },
  { id: "ruby-rose", title: "Ruby Rose", size: "5x7 in", thick: false, price: 40, shipping: 5, sold: false },
  { id: "violet-bloom", title: "Violet Bloom", size: "5x7 in", thick: false, price: 40, shipping: 5, sold: false },
  { id: "silver-daisies", title: "Silver Daisies", size: "5x7 in", thick: false, price: 40, shipping: 5, sold: false },
  { id: "white-daisy", title: "White Daisy", size: "5x7 in", thick: false, price: 40, shipping: 5, sold: false },
  { id: "neon-peony", title: "Neon Peony", size: "5x7 in", thick: false, price: 40, shipping: 5, sold: false },
  { id: "hibiscus", title: "Hibiscus", size: "5x7 in", thick: false, price: 40, shipping: 5, sold: false },
  { id: "purple-pansy", title: "Purple Pansy", size: "5x7 in", thick: false, price: 40, shipping: 5, sold: false },
  { id: "pink-tulip", title: "Pink Tulip", size: "5x7 in", thick: false, price: 40, shipping: 5, sold: false },
  { id: "black-pansy", title: "Black Pansy", size: "5x7 in", thick: false, price: 40, shipping: 5, sold: false },
  { id: "lion-sunflower", title: "Lion Sunflower", size: "4x6 in", thick: false, price: 30, shipping: 5, sold: false },
  { id: "anatomical-heart", title: "Anatomical Heart", size: "4x6 in", thick: false, price: 30, shipping: 5, sold: false },
  { id: "crimson-rose", title: "Crimson Rose", size: "4x6 in", thick: false, price: 30, shipping: 5, sold: false },
  { id: "pink-orchid", title: "Pink Orchid", size: "4x6 in", thick: false, price: 30, shipping: 5, sold: false },
  { id: "red-rose", title: "Red Rose", size: "4x6 in", thick: false, price: 30, shipping: 5, sold: false },
  { id: "violet-rose", title: "Violet Rose", size: "4x6 in", thick: false, price: 30, shipping: 5, sold: false },
  { id: "violet-star", title: "Violet Star", size: "4x6 in", thick: false, price: 30, shipping: 5, sold: false },
  { id: "red-dahlia", title: "Red Dahlia", size: "4x6 in", thick: false, price: 30, shipping: 5, sold: false },
  { id: "pink-peony", title: "Pink Peony", size: "4x6 in", thick: false, price: 30, shipping: 5, sold: false },
  { id: "swirl-pansy", title: "Swirl Pansy", size: "4x6 in", thick: false, price: 30, shipping: 5, sold: false },
  { id: "jeweled-sunflower", title: "Jeweled Sunflower", size: "4x4 in", thick: true, price: 25, shipping: 5, sold: false },
  { id: "emerald-star", title: "Emerald Star", size: "4x4 in", thick: true, price: 25, shipping: 5, sold: false },
  { id: "emerald-mosaic", title: "Emerald Mosaic", size: "4x4 in", thick: true, price: 25, shipping: 5, sold: false },
];
